general:
  logo_image: /images/legacy-green-logo.png
  logo-max-width: 100%
  menu-logo_image: /images/legacy-green-logo.png
  explore-logo_image: /images/legacy-green-logo-white.png
technical:
  fonts-embed: >-
    <link rel="preconnect" href="https://fonts.googleapis.com">  <link
    rel="preconnect" href="https://fonts.gstatic.com" crossorigin>  <link
    href="https://fonts.googleapis.com/css2?family=Livvic:wght@300;400;500;600;700&display=swap"
    rel="stylesheet">
  google-analytics-id: G-EGPJXNJ2Z8
  cookie-banner-cta-name: More information
  cookie-banner-cta-url: /privacy-policy
  cookie-banner-approve: Approve
  stuff-for-head:
seo:
  site_name: Legacy Green Cleaning Services | Commercial Green Cleaning
  title: Legacy Green Cleaning Services | Commercial Green Cleaning
  description:
  keywords:
  social_image: /images/legacy-green-logo.png
social:
  instagram_url: https://www.instagram.com/legacygreen.au/
  facebook_url: https://www.facebook.com/profile.php?id=100083023674310
  tik-tok_url: https://www.tiktok.com/@legacygreen.au
  youtube_url:
  pinterest_url:
  twitter_url:
  linkedin_url:
